CREATE TABLE [dbo].[Groups]
(
	[GroupId] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(256) NOT NULL,
	CONSTRAINT PK_Groups PRIMARY KEY CLUSTERED ([GroupId])
);
GO

CREATE UNIQUE NONCLUSTERED INDEX [UX_Groups_Name] ON [dbo].[Groups] ([Name]);
GO