CREATE TABLE [dbo].[UserGroups]
(
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[GroupId] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT PK_UserGroups PRIMARY KEY CLUSTERED ([UserId],[GroupId]),
	CONSTRAINT FK_UserGroups_User FOREIGN KEY ([UserId]) REFERENCES [dbo].[Users] (UserId) ON DELETE CASCADE,
	CONSTRAINT FK_UserGroups_Group FOREIGN KEY ([GroupId]) REFERENCES [dbo].[Groups] (GroupId) ON DELETE CASCADE
);
GO
