CREATE TABLE [dbo].[Users]
(
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[EmailAddress] NVARCHAR(256) NOT NULL,
	[DisplayName] NVARCHAR(256) NOT NULL,
	[TypeId] UNIQUEIDENTIFIER NOT NULL,
	[IsActive] BIT NOT NULL CONSTRAINT [Default_Users_IsActive] DEFAULT 0,
	CONSTRAINT PK_Users PRIMARY KEY CLUSTERED ([UserId]),
	CONSTRAINT FK_Users_Type FOREIGN KEY ([TypeId]) REFERENCES [dbo].[UserTypes] (UserTypeId)
);
GO

CREATE UNIQUE NONCLUSTERED INDEX [UX_Users_EmailAddress] ON [dbo].[Users] ([EmailAddress]);
GO