CREATE TABLE [dbo].[Groups]
(
	[GroupId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(256) NOT NULL UNIQUE
);
GO

CREATE TABLE [dbo].[Permissions]
(
	[PermissionId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(256) NOT NULL UNIQUE
);
GO

CREATE TABLE [dbo].[UserTypes]
(
	[UserTypeId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(256) NOT NULL UNIQUE
);
GO

CREATE TABLE [dbo].[Users]
(
	[UserId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[EmailAddress] NVARCHAR(256) NOT NULL UNIQUE,
	[DisplayName] NVARCHAR(256) NOT NULL,
	[UserTypeId] UNIQUEIDENTIFIER NOT NULL,
	[IsActive] BIT NOT NULL DEFAULT 0,
	CONSTRAINT FK_Users_Type FOREIGN KEY ([UserTypeId]) REFERENCES [dbo].[UserTypes] (UserTypeId)
);
GO

CREATE TABLE [dbo].[UserGroups]
(
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[GroupId] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT PK_UserGroups PRIMARY KEY CLUSTERED ([UserId],[GroupId]),
	CONSTRAINT FK_UserGroups_User FOREIGN KEY ([UserId]) REFERENCES [dbo].[Users] (UserId) ON DELETE CASCADE,
	CONSTRAINT FK_UserGroups_Group FOREIGN KEY ([GroupId]) REFERENCES [dbo].[Groups] (GroupId) ON DELETE CASCADE
);
GO

CREATE TABLE [dbo].[UserPermissions]
(
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[PermissionId] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT PK_UserPermissions PRIMARY KEY CLUSTERED ([UserId],[PermissionId]),
	CONSTRAINT FK_UserPermissions_User FOREIGN KEY ([UserId]) REFERENCES [dbo].[Users] (UserId) ON DELETE CASCADE,
	CONSTRAINT FK_UserPermissions_Permission FOREIGN KEY ([PermissionId]) REFERENCES [dbo].[Permissions] (PermissionId) ON DELETE CASCADE
);
GO
